CREATE TABLE ML_MODEL (
  id NUMBER PRIMARY KEY,
  name VARCHAR2(255),
  description VARCHAR2(255),
  loss_fn VARCHAR2(65532),
  optimizer VARCHAR2(65532)
);

CREATE SEQUENCE SEQ_ML_MODEL NOCYCLE;

CREATE TABLE ML_MODEL_LAYER (
  id NUMBER PRIMARY KEY,
  mid NUMBER REFERENCES ML_MODEL(id),
  layer VARCHAR2(65532)
);

CREATE SEQUENCE SEQ_ML_MODEL_LAYER NOCYCLE;

CREATE TABLE ML_INFERENCE (
  id NUMBER PRIMARY KEY,
  data BLOB
);

CREATE SEQUENCE SEQ_ML_INFERENCE NOCYCLE;

CREATE TABLE ML_TRAIN (
  id NUMBER PRIMARY KEY,
  mid NUMBER REFERENCES ML_MODEL(id),
  kernel CHAR(36),
  status CHAR(50),
  path VARCHAR2(65532)
);

CREATE SEQUENCE SEQ_ML_TRAIN NOCYCLE;

CREATE TABLE ML_TRAIN_LOG (
  tid NUMBER REFERENCES ML_TRAIN(id),
  log VARCHAR2(65532),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);