DROP TABLE sys.ML_TRAIN_LOG;
DROP TABLE sys.ML_TRAIN;
DROP TABLE sys.ML_MODEL_LAYER;
DROP TABLE sys.ML_MODEL;
DROP TABLE sys.ML_INFERENCE;

DROP SEQUENCE sys.SEQ_ML_MODEL;
DROP SEQUENCE sys.SEQ_ML_MODEL_LAYER;
DROP SEQUENCE sys.SEQ_ML_INFERENCE;
DROP SEQUENCE sys.SEQ_ML_TRAIN;