DROP TABLE ML_TRAIN_LOG;
DROP TABLE ML_TRAIN;
DROP TABLE ML_MODEL_LAYER;
DROP TABLE ML_MODEL;
DROP TABLE ML_INFERENCE;

DROP SEQUENCE SEQ_ML_MODEL;
DROP SEQUENCE SEQ_ML_MODEL_LAYER;
DROP SEQUENCE SEQ_ML_INFERENCE;
DROP SEQUENCE SEQ_ML_TRAIN;